### PR TITLE
0.15 features

### LINKED ISSUE #1538: Latex container dupe bug with fatal crash.
Note that this bug is on the current 0.15-features branch.

Latex containers on contact with water end up breaking themselves, turning into two separate top halves then 'falling' like an anvil or a sand block. This ends up glitching them out constantly breaking themselves, replacing themselves and duplicating themselves as well. Found this on accident when testing out the new maintenance area. I also suffered a fatal crash maybe a minute or two after this.

Further testing shows that the problem is made much worse when goo is added to the container, generating crashes every time the block falls and also putting people on singleplayer worlds into a crash loop. It's also shown that if a latex container is dropped onto flowing water, the code for the latex container to fully break when registering a fall seems to always be executed first before the bug can take effect. Placing a latex container underwater duplicates the container yet the container doesn't end up replacing itself, showing that the glitch needs the upper top half to survive to function. While testing that development, I've also found that if you put a block above the latex container's upper half it deletes that block when replacing itself, which includes bedrock.

It should be noted that I have four separate mods installed as well, JEI, JER, Carpet: NeoForged and Configured. None of these mods should be causing this critical bug.

Here's my first crash report from when the bug originally happened to me.
[ContainerCrashReport.txt](https://github.com/user-attachments/files/23248971/ContainerCrashReport.txt)

Here's a few images showing off some of the quirks of this bug

These show the bug in action, where it breaks into two top halves then the 'bottom top half' getting broken by the water again, which causes the 'upper top half' to reform back into a full container when updated, occupying both the space where that half was and the space above it, deleting any blocks placed there in the process.

Image

Image

Image

### LINKED ISSUE #1545: Buffer inconsistent in EmoteParticleOption
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/fea4476ca582ecb64e1cb98900e2749ea15dfa4f/src/main/java/net/ltxprogrammer/changed/effect/particle/EmoteParticleOption.java#L63

It try to read two values while writing only 1

Just make it write the entity id in the buffer

### LINKED ISSUE #1552: Array out of bounds
There is a issue in ‎src/main/java/net/ltxprogrammer/changed/mixin/client/ChunkRenderDispatcherMixin.java‎ in the getLatexCoverState which try to get a array index that is out of bounces

To fix that i did in my fork a simple accessor in the RenderChunkRegion to get the level and then used that level to get the chunk using the i and j and it works fine and didn't cause the crash anymore

Should i make a pull request? I also post the version in the "maven" but i can just delete that files

### PR DESCRIPTION
**Pull request by Foxyas**
Updated pt_br
Added Lang Keys for new attributes for en_us
Fixed #1538 for 1.20.1
Fixed #1545 for 1.20.1
Fixed #1552 for 1.20.1
Fixed Mixin compatibility.Forgery.LatexHumanoidArmorLayerMixin using old renderModel method.
 *Side Note: it didn't stop me from compiling the mod, whoever it is something to fix? idk for sure soo i just let the old code commented and the "new code" applied down below*
Fixed Weird "ride" animation when laying down into a bed with the mod "sleep tight"
Fixed ColorSelector$renderWidget not rendering the colors
 *it was using 0x00colorInt instead of 0xffcolorint*
Fixed Breathing Bug where the player would lost air even with Water Breathing Effect. 
*also added a simple check for compatibility.. who knows right?*

Create a Temp mixin to fix the accesstransformer not applying the "remove final" from FluidType$isAir
Added some datagens to help with the dev
  - to use just call add (or similar) in the file and then run the task "runData"
  - the folder where it stores the generated files are `generated/resources`
  - Embedium or any other client side mod will crash the runData task so be careful

publish w.i.p version into maven to help addon dev's :>

## Proposed Future Changes (Need approval from main dev first)
- [ ] - Add Interface ICrawlEntity 
    - will make any changed entity able to have the "safe pose check" feature similar to the player
    - will make any changed entity also able to enter into "crawl mode" if they target is in crawl pose
- [ ] - Add Interface IGrabberEntity
    - will make any changed entity able to use the grab ability
    - gonna be a dependence for "grab target goals"
- [ ] - Add a ´/accessory´ command that gonna allow any admin to set a accessory for any entity/entities
    - Dynamic slot suggestion system (only show the slots that the entity have and if something bad happen that the code return a invalid state exception will just show all the slots registred)
    - Dynamic FeedBack to tell the command executor what wrong happen
- [ ] - Add Face/Head Accessory Slot
    - For the Income features :>

### CODE REVIEW

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java [hunk 1]
```diff
@@ -377,10 +373,13 @@ public RenderType getRenderType(LatexCoverState coverState) {
     }
 
 
-    @Nullable
-    private static LatexCoverGetter latexCoverStateGetter = null;
+//    Old Code
+//    @Nullable
+//    private static LatexCoverGetter latexCoverStateGetter = null;
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java]: No need to leave old code in a comment, the diff on git is enough.

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java [hunk 2]
```diff
@@ -480,7 +483,7 @@ public boolean tesselate(
         } catch (Throwable throwable) {
             CrashReport crashreport = CrashReport.forThrowable(throwable, "Tesselating latex cover in world");
             CrashReportCategory crashreportcategory = crashreport.addCategory("Block being tesselated");
-            CrashReportCategory.populateBlockDetails(crashreportcategory, level, blockPos, (BlockState)null);
+            CrashReportCategory.populateBlockDetails(crashreportcategory, level, blockPos, (BlockState) null);
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java]: The code base uses C-style casting all over the place. This formatting adjustment is not necessary.

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java [hunk 3]
```diff
@@ -527,13 +530,13 @@ private static CompletableFuture<Map<Block, LatexModelDefinition>> loadBlockStat
...
     static <T extends Comparable<T>> T getValueHelper(Property<T> property, String p_119278_) {
-        return property.getValue(p_119278_).orElse((T)null);
+        return property.getValue(p_119278_).orElse((T) null);
     }
 
     private static Predicate<BlockState> predicate(StateDefinition<Block, BlockState> stateDefinition, String text) {
         Map<Property<?>, Comparable<?>> map = Maps.newHashMap();
 
-        for(String s : COMMA_SPLITTER.split(text)) {
+        for (String s : COMMA_SPLITTER.split(text)) {
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java:531]: Unlike the comment on casting, this is a change I do appreciate. This instance was likely a holdover from copying Minecraft's source.

File: src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java [hunk 4]
```diff
@@ -851,11 +852,13 @@ protected void tickBreathing() {
             }
         }
 
-        if (!host.level().isClientSide)
+        if (!host.level().isClientSide) {
+            if (host.hasEffect(MobEffects.WATER_BREATHING) || !host.canDrownInFluidType(ForgeMod.WATER_TYPE.get())) return;
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java]: This fix is in the wrong place. It should instead be where the code specifically checks breathing underwater (line 805).

File: src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: Wouldn't this fix be simpler if you instead overwrote the conditions for `HumanoidAnimator.AnimateStage.RIDE` and `HumanoidAnimator.AnimateStage.SLEEP`?

File: src/main/java/net/ltxprogrammer/changed/fluid/Gas.java [hunk 5]
```diff
@@ -41,10 +41,10 @@ public GasFluidType(Properties properties) {
...
         }
 
-        @Override
-        public boolean isAir() { // Requires accesstransformer to work
-            return true;
-        }
+//        @Override
+//        public boolean isAir() { // Requires accesstransformer to work
+//            return true;
+//        } // For some Reason the Access Transformer stop working? check the FluidTypeMixin
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: This could be a dev env bug. I would need to test myself.

File: src/main/java/net/ltxprogrammer/changed/mixin/client/RenderChunkRegionAccessor.java
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/mixin/client/RenderChunkRegionAccessor.java:1]: Vestigial accessor? I don't see any references to it elsewhere.

File: src/main/java/net/ltxprogrammer/changed/mixin/compatibility/Forgery/LatexHumanoidArmorLayerMixin.java
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/mixin/compatibility/Forgery/LatexHumanoidArmorLayerMixin.java:1]: I'm aware of a few cases where the IDE warns on target methods, but there is no need for the changes present in this file.

File: src/main/java/net/ltxprogrammer/changed/datagen/ability_tree/AbilityTreeProviderImpl.java
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/datagen/ability_tree/AbilityTreeProviderImpl.java:1]: Currently serves no purpose other than to showcase an example on how to use it.

File: gradle.properties [hunk 6]
```diff
@@ -7,7 +7,7 @@ org.gradle.daemon=false
 javaVersion = 17
 
 runWithClientOnlyMods = true
-runWithMods = embeddium,oculus,presencefootsteps,spark,modernfix,ferritecore,entityculling,debugutils
+runWithMods = embeddium,oculus,presencefootsteps,spark,modernfix,ferritecore,entityculling,debugutils,sleep_tight,moonlight_lib
```
Comment (LtxProgrammer) [inline gradle.properties]: I know I never said this, but the mods that are in this list are intended to be vital in the run environment. Mods that are present in this list only for debugging a compatibility should not be committed.

File: src/main/java/net/ltxprogrammer/changed/mixin/client/ChunkRenderDispatcherMixin.java [hunk 7]
```diff
@@ -34,12 +36,20 @@
...
 
     @Unique
     public LatexCoverState getLatexCoverState(RenderChunkRegion region, BlockPos blockPos) {
         int i = SectionPos.blockToSectionCoord(blockPos.getX()) - region.centerX;
         int j = SectionPos.blockToSectionCoord(blockPos.getZ()) - region.centerZ;
+
+
+        //Old Fail Safe
+        //if (i < 0 || i >= region.chunks.length) return ChangedLatexTypes.NONE.get().defaultCoverState();
+        //if (j < 0 || j >= region.chunks[0].length) return ChangedLatexTypes.NONE.get().defaultCoverState();
```
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/mixin/client/ChunkRenderDispatcherMixin.java]: Vestigial commented-out code.

**Review by LtxProgrammer — CHANGES_REQUESTED** [review]
Please see review comments.

File: gradle.properties (hunk 6 above)
Comment (Foxyas) [reply gradle.properties]: Oops.. i forgot to remove it :p

Comment (Foxyas) [reply gradle.properties]: Oops.. i forgot to remove it :p

File: src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: I tried and the animation still happen which looks odd.. i gonna try doing more tweaks

File: src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java (hunk 4 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java]: Ohh okay, i just thought that tickBreathing was the right place :p

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java]: Ohh okay, i just thought that tickBreathing was the right place :p

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java (hunk 2 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java]: InteliJ auto did it when i did the "optimize imports" thing

File: src/main/java/net/ltxprogrammer/changed/mixin/client/RenderChunkRegionAccessor.java
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/client/RenderChunkRegionAccessor.java:1]: is from my old fix i gonna remove it

File: src/main/java/net/ltxprogrammer/changed/mixin/compatibility/Forgery/LatexHumanoidArmorLayerMixin.java
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/Forgery/LatexHumanoidArmorLayerMixin.java:1]: i check it again, and there's fr no method with this dependencies
```java
renderModel(T entity, ItemStack stack, EquipmentSlot slot, PoseStack pose, MultiBufferSource buffers, int packedLight, boolean foil, LatexHumanoidArmorModel<T, ?> model, float red, float green, float blue, ResourceLocation armorResource)
```

the most similar is this 
```java
renderModel(T entity, ItemStack stack, EquipmentSlot slot, PoseStack pose, MultiBufferSource buffers, int packedLight, LatexHumanoidArmorModel<? super T, ?> model, float red, float green, float blue, ResourceLocation armorResource)
```

i check again and the old method is from 1.18.2 
this line to be specific -> https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/fea4476ca582ecb64e1cb98900e2749ea15dfa4f/src/main/java/net/ltxprogrammer/changed/client/renderer/layers/LatexHumanoidArmorLayer.java#L101

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java (hunk 1 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java]: i tweaked

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java (hunk 2 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java]: i tweaked

File: src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java (hunk 3 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/client/LatexCoveredBlocksRenderer.java:531]: the idea was (@0SeNiA0) idea :p

File: src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java (hunk 4 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java]: i tweaked

File: src/main/java/net/ltxprogrammer/changed/fluid/Gas.java (hunk 5 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: alright i will let that then

File: src/main/java/net/ltxprogrammer/changed/datagen/ability_tree/AbilityTreeProviderImpl.java
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/datagen/ability_tree/AbilityTreeProviderImpl.java:1]: i removed the class but keep the main datagen thing

File: gradle.properties (hunk 6 above)
Comment (Foxyas) [reply gradle.properties]: i tweaked

File: src/main/java/net/ltxprogrammer/changed/mixin/client/ChunkRenderDispatcherMixin.java (hunk 7 above)
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/client/ChunkRenderDispatcherMixin.java]: i removed the old code comment :P

**Comment by Foxyas** [comment]
@LtxProgrammer do you want to me to remove the maven files?

**Comment by Foxyas** [comment]
oh so it should reset the value. okay

File: src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java (hunk 4 above)
Comment (LtxProgrammer) [reply src/main/java/net/ltxprogrammer/changed/entity/variant/TransfurVariantInstance.java]: I pushed a commit to properly handle this case.

**Comment by LtxProgrammer** [comment]
> oh so it should reset the value. okay

`ticksBreathingUnderwater` is to track how long the entity has relied on their own ability to breathe water in order to progress the advancement.

`airDelta` is how much the air will change that tick. Positive adds air, and negative subtracts.

**Comment by Foxyas** [comment]
> > oh so it should reset the value. okay
> 
> `ticksBreathingUnderwater` is to track how long the entity has relied on their own ability to breathe water in order to progress the advancement.
> 
> `airDelta` is how much the air will change that tick. Positive adds air, and negative subtracts.

soo the player will gain air with a water breath potion? correct me if i'm wrong but the potion effect does that normaly?

**Comment by Foxyas** [comment]
If I remember correctly, the potion prevents loss of air. But if the player drinks the potion after losing some "Breath Ticks," the player will still retain the same breath ticks without recovering them. Which I think doesn't make much sense in a certain way.
"Water Breathing"

**Comment by LtxProgrammer** [comment]
> @LtxProgrammer do you want to me to remove the maven files?

My only concern with the maven files is the existence of a published copy of the jar.

> soo the player will gain air with a water breath potion? correct me if i'm wrong but the potion effect does that normaly?

You are correct, I hastily modified the code without reviewing vanilla behavior. I don't know why Mojang named it "water breathing" if the player isn't "breathing" the water. I'll revert the change.

**Comment by Foxyas** [comment]
> > @LtxProgrammer do you want to me to remove the maven files?
> 
> My only concern with the maven files is the existence of a published copy of the jar.
> 
> > soo the player will gain air with a water breath potion? correct me if i'm wrong but the potion effect does that normaly?
> 
> You are correct, I hastily modified the code without reviewing vanilla behavior. I don't know why Mojang named it "water breathing" if the player isn't "breathing" the water. I'll revert the change.

yeah mojang really need to redo some features logic LOL

File: src/main/java/net/ltxprogrammer/changed/fluid/Gas.java (hunk 5 above)
Comment (LtxProgrammer) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: I was able to compile and run the mod without the above fix. You may have not run the correct steps to compile after an accesstransformer change (genIntellijRuns).

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: bruh....

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: nop.. it's still broken

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: i got it fixed @LtxProgrammer i just had to update the file with another access transformer

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/fluid/Gas.java]: aka i add this line
```java
public net.minecraft.world.damagesource.CombatTracker f_19282_ # takingDamage
```
which gonna be useful for the exoskeleton

File: src/main/java/net/ltxprogrammer/changed/item/ExoskeletonItem.java
Comment (LtxProgrammer) [inline src/main/java/net/ltxprogrammer/changed/item/ExoskeletonItem.java:1]: This change is no longer necessary.

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/item/ExoskeletonItem.java:1]: okay

**Comment by Foxyas** [comment]
@LtxProgrammer do you wanna for me to commit the /accessory command?

**Comment by LtxProgrammer** [comment]
> @LtxProgrammer do you wanna for me to commit the /accessory command?

If you can do it well, but only after resolving my comment on the sleep tight mod.

File: src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java
Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: i gonna try again, applying other check now

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: i gonna apply a mixin into HumanoidAnimator.AnimateStage$test which i probably think that will work

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: image
it works

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: image
the "normal sleep"

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: i need to tweak the offset tho

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: image
i got it working but the hitbox is abit off...
however the hitbox that is out of the bed is the "bed entity" not the player one

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: @LtxProgrammer should i apply a animation mixin to offset the whole root of the model or just keep it was it is?

Comment (LtxProgrammer) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: What does it look like for a humanoid latex?

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: > What does it look like for a humanoid latex?

for humanoids the hitbox is still glued to the bed, but still has a bit of offset.
it looks VERY similar to the "true sleeping position" too
image

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: @LtxProgrammer i already made a better handle
image
image

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: i still need todo some for the quadrupdals

Comment (Foxyas) [reply src/main/java/net/ltxprogrammer/changed/mixin/compatibility/SleepTight/ArmRideAnimatorMixin.java:1]: anyway i gonna do a simple "switch" for the offset

**Comment by Foxyas** [comment]
@LtxProgrammer i probably made all the needed changes into the compatibility with sleep Tight

it now uses the livingRenderer setUpRotations instead of the "rider position" soo the hitbox is right

i made a offset multiplier for each entity shape instead of entity instance types

**Comment by Foxyas** [comment]
The accessory item thing will probably take a while to be commited cuz a heavy storm is reaching my region and i really don't want to risk using my pc while that.

**Review by LtxProgrammer — APPROVED** [review]

**Comment by LtxProgrammer** [comment]
> The accessory item thing will probably take a while to be commited cuz a heavy storm is reaching my region and i really don't want to risk using my pc while that.

Very well, it can be in another PR. What are you worried about with the storm, an electric surge? You should get a surge protector. Or a UPS if its a blackout you're worried about.

**Comment by Foxyas** [comment]
@LtxProgrammer btw, would you allow me to add the grab feature for entities?

I can make where entities only try to grab the player if they are inside of a "can grab" tag.

Check changed addon repository for examples

Check the interface "IGrabberEntity"

**Comment by Foxyas** [comment]
> > The accessory item thing will probably take a while to be commited cuz a heavy storm is reaching my region and i really don't want to risk using my pc while that.
> 
> Very well, it can be in another PR. What are you worried about with the storm, an electric surge? You should get a surge protector. Or a UPS if its a blackout you're worried about.

Yeah basically that. And yeap i gonna buy one when i got some money :p
