### PR TITLE
Update Lang, Fixed Issues, Grab Struggle Attribute

### LINKED ISSUE #1597: cover state struck by lightning logic tweak!
i made a oops and forgot to commit the logic tweak where it would not affect player in spectator or creative!
@LtxProgrammer you can just apply a 1 line check in the foreach of the living entities to check if it is a player and if they are in creative or spectator!
i'm sorry about that.

the fix is too little to make a whole pull request but it's still annoying

### PR DESCRIPTION
**Pull request by Foxyas**
Fixes #1597 

## Proposed Changes
  - Grab Struggle now is handled by a entity attribute other than a constante
   * Added a fail safe for entities that don't has such attribute 
  - Added a "Non Creative / Spectator" check for the onStruckByLighting method
  - updated pt_br

### CODE REVIEW

File: src/main/java/net/ltxprogrammer/changed/ability/GrabEntityAbilityInstance.java [hunk 1]
```diff
@@ -306,8 +307,23 @@ else if (instructionTicks == -60 && this.grabbedEntity instanceof Player) // Onl
     public void handleEscape() {
         ticksGrabbed++;
 
+        float entityGrabStrengthDecay = this.suited ? GRAB_STRENGTH_DECAY_SUITED : GRAB_STRENGTH_DECAY;
```
Comment (Foxyas) [inline src/main/java/net/ltxprogrammer/changed/ability/GrabEntityAbilityInstance.java:310]: this is a fail safe for if the entity don't have the attribute.
that value is not supposed to be used but is better to have it than don't

**Comment by Foxyas** [comment]
fun fact, when the player get transfured they grab struggle get lowed because the changed entities has a default value of ~0.05 instead of ~0.21.
This "problem" doesn't bother at all, because the entities/players shouldn't be able to grab transfured players.

**Review by LtxProgrammer — APPROVED** [review]
